"""Rate-distortion theory — monograph Part II.

Table 2.1 is regenerated by numerical integration rather than transcribed, so
E5 can check the monograph's own table as a prediction instead of trusting it
as an input. Appendix B is used only as a cross-check.
"""

from __future__ import annotations

import numpy as np
from scipy import integrate, optimize, stats

# Panter-Dite constant for a Gaussian source: (integral f^{1/3})^3 / 12,
# giving D* = (sqrt(3)*pi/2) * sigma^2 * 2^{-2b}.
PANTER_DITE_GAUSS = float(np.sqrt(3) * np.pi / 2)  # 2.7207


def expected_max_normal(n: int) -> float:
    """E[max] of n i.i.d. standard normals, by direct integration.

    E[max] = n * integral x phi(x) Phi(x)^{n-1} dx.
    """

    def f(x: float) -> float:
        return n * x * stats.norm.pdf(x) * stats.norm.cdf(x) ** (n - 1)

    val, _ = integrate.quad(f, -12, 12, limit=400)
    return float(val)


def expected_max_asymptotic(n: int) -> float:
    """§2.3 asymptotic form. Underestimates at small n — kept for comparison."""
    L = np.log(n)
    return float(
        np.sqrt(2 * L) - (np.log(L) + np.log(4 * np.pi)) / (2 * np.sqrt(2 * L))
    )


def expected_range(G: int) -> float:
    """E[R_G]/sigma under (A3): symmetric, so range = 2 * E[max]."""
    return 2.0 * expected_max_normal(G)


def distortion_grouped(b: int, G: int) -> float:
    """D/sigma^2 for grouped uniform min-max quantization (Table 2.1)."""
    delta = expected_range(G) / ((1 << b) - 1)
    return float(delta * delta / 12.0)


def sqnr_grouped_db(b: int, G: int) -> float:
    return float(-10.0 * np.log10(distortion_grouped(b, G)))


def distortion_log_law(b: int, G: int) -> float:
    """Prop 2.6 — the asymptotic 2 ln G / (3 (2^b-1)^2) form."""
    return float(2.0 * np.log(G) / (3.0 * ((1 << b) - 1) ** 2))


def distortion_panter_dite(b: int) -> float:
    """Thm/eq. §2.5 — globally optimal companded quantizer, Gaussian source."""
    return float(PANTER_DITE_GAUSS * 2.0 ** (-2 * b))


def optimal_clip(b: int) -> float:
    """§2.8 — alpha* minimizing granular + overload distortion, in sigma."""

    def D(alpha: float) -> float:
        if alpha <= 0:
            return np.inf
        granular = (2 * alpha) ** 2 / (12.0 * 4.0**b)

        def tail(x: float) -> float:
            return (x - alpha) ** 2 * stats.norm.pdf(x)

        overload, _ = integrate.quad(tail, alpha, alpha + 20, limit=400)
        return granular + 2.0 * overload

    res = optimize.minimize_scalar(
        D, bounds=(0.3, 8.0), method="bounded", options={"xatol": 1e-6}
    )
    return float(res.x)


def outlier_distortion(G: int, b: int, outlier_sigma: float) -> float:
    """Prop 2.10 — one value at `outlier_sigma` inside an otherwise clean group.

    The range becomes ~2 * outlier_sigma (the outlier sets one end, and by
    symmetry a comparable value can set the other), which is the monograph's
    R ~ 20 sigma for a 10 sigma outlier.
    """
    R = 2.0 * outlier_sigma
    delta = R / ((1 << b) - 1)
    return float(delta * delta / 12.0)


def outlier_rate_penalty(p: float) -> float:
    """Prop 2.11 — bits/weight added by storing fraction p as fp16 + uint16."""
    return 32.0 * p


def table_2_1(b: int = 4, groups=(16, 32, 64, 128, 256)) -> list[dict]:
    """Regenerate Table 2.1 from first principles."""
    rows = []
    for G in groups:
        R = expected_range(G)
        delta = R / ((1 << b) - 1)
        D = delta * delta / 12.0
        rows.append(
            {
                "G": G,
                "E_range_over_sigma": R,
                "delta_over_sigma": delta,
                "D_over_sigma2": D,
                "sqnr_db": -10.0 * np.log10(D),
            }
        )
    return rows
